### ISSUE TITLE
maj01 function doesn't seem quite right

### ISSUE THREAD

**Issue by twalenczyk** [notmattmoore/quantum-algorithms#8]
In simon-experiment/sum.py, **maj01** returns args[1] if count(args[1]) > count(args[2]) and args[0] otherwise. (Psuedo-code for brevity.) But, if args[0]=args[1], the result of the function can diverge from the expected result. For instance, if args=[1,1,0,0,0], we would expect **maj01** to return 0. However, as it is written, **maj01** returns 1.

If my interpretation is correct, this is a quick fix.

**Comment by twalenczyk** [comment]
Of course, this bit of code may now be out of date with the introduction of the post_ops module.

**Comment by notmattmoore** [comment]
I guess the function name is misleading. maj01 is actually a general near unanimity (NU) operation, meaning it satisfies n(y,x,...,x) = n(x,y,x,...,x) = ... = x. A 3-ary NU is called a majority function.

**Comment by twalenczyk** [comment]
Ahhh, now THAT makes sense!
